language: python

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
#    - sudo: required
#      services:
#        - docker
#      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
#           PRE_CMD=linux32
#           PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh c-f-h ilupp master
  - ls wheelhouse/

after_success:
  - cd wheelhouse
  - |
    for whl in *manylinux*whl
    do
      curl -T $whl -u "HdsFBcaAiPGZ5kn:" https://nextcloud03.webo.hosting/public.php/webdav/    
    done
